services:
  webserver:
    image: belalelnady/php-mysql-views-counter:latest
    container_name: views-counter
    ports:
      - "7799:80"
    networks:
      - mynet
    depends_on:
      - mysqlDB

  mysqlDB:
    image: mysql:latest
    container_name: mysqlDB
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: belal
      MYSQL_PASSWORD: belal
      MYSQL_DATABASE: views
    networks:
      - mynet
    volumes:
      - myvol2:/var/lib/mysql

networks:
  mynet:
    driver: bridge
volumes:
  myvol2:
    